<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- ############################################################################### -->
    <!-- Basic plugin configuration, start here -->
    <!-- ############################################################################### -->
    <groupId>dev.shadmage</groupId>
    <artifactId>eggemall</artifactId>
    <name>EggEmAll2</name>
    <version>1.0.1</version>
    <packaging>jar</packaging>

    <properties>
        <author>shadmage</author>
        <!-- The full path to your plugin's main class, so that Spigot can find and load it -->
        <main.class>dev.shadmage.eggemall2.EggEmAllPlugin</main.class>
        <!-- ======================================================================================================= -->
        <foundation.version>6.2.9</foundation.version> <!-- https://github.com/kangarko/Foundation/releases -->
        <foundation.path>com.github.kangarko</foundation.path>
        <mavencompiler.version>3.10.1
        </mavencompiler.version> <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
        <mavenshade.version>3.3.1-SNAPSHOT
        </mavenshade.version> <!-- https://repository.apache.org/content/repositories/snapshots/org/apache/maven/plugins/maven-shade-plugin/ -->
        <mavenjarplugin.version>3.3.0
        </mavenjarplugin.version> <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>maven-snapshots</id>
            <url>https://repository.apache.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>${foundation.path}</groupId>
            <artifactId>Foundation</artifactId>
            <version>${foundation.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.name}-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${mavenjarplugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${mavencompiler.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${mavenshade.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <artifactSet>
                        <includes>
                            <include>${foundation.path}:Foundation*</include>
                        </includes>
                    </artifactSet>
                    <relocations>
                        <!-- Move the Foundation library into your own package in "lib" subpackage to prevent interference. -->
                        <relocation>
                            <pattern>org.mineacademy.fo</pattern>
                            <shadedPattern>${project.groupId}.${project.artifactId}.lib</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>