name: ${project.name}
version: ${project.version}
main: ${main.class}
author: ${author}
api-version: 1.13
softdepend: [ CMI, Vault, GriefPrevention, AuthMe, BanManager, BungeeChatAPI, DiscordSRV, Factions, Feudal, ItemsAdder, Essentials, LegacyFactions, Lands, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, mcMMO, NashornPlus, Nicky, PlaceholderAPI, ProtocolLib, SimpleClans, Towny, TownyChat, WorldEdit ]
website: www.dirtydogsa.co.za

permissions:
  eggemall.all:
    description: Gives access to catch all types of mobs.
    default: op
    children:
      eggemall.villagers: true
      eggemall.aggressive: true
      eggemall.passive: true
      eggemall.unknown: true